#index:
#    path: /
#    controller: App\Controller\DefaultController::index


categoria:
    path: /categoria
    controller: App\Controller\CategoriaController::index

categoriadicionar:
    path: /categoriaadicionar
    controller: App\Controller\CategoriaController::adicionar

categoriaeditar:
    path: /categoriaeditar/{id}
    controller: App\Controller\CategoriaController::editar


produto:
    path: /produto
    controller: App\Controller\ProdutoController::index

produtoadicionar:
    path: /produtoadicionar
    controller: App\Controller\ProdutoController::adicionar

