#index:
#    path: /
#    controller: App\Controller\DefaultController::index


categoria:
    path: /categoria
    controller: App\Controller\CategoriaController::index

produto:
    path: /produto
    controller: App\Controller\ProdutoController::index

categoriaadicionar:
    path: /categoriaadicionar
    controller: App\Controller\CategoriaController::adicionar
    
produtoadicionar:
    path: /produtoadicionar
    controller: App\Controller\ProdutoController::adicionar
